---
- name: Install Nginx
  apt: name=nginx state=present

- name: Start Nginx service
  service: name=nginx state=started enabled=true

- name: ensure phpmyadmin ppa repository is installed
  apt_repository:
    repo: "ppa:nijel/phpmyadmin"
    update_cache: yes

- name: ensure phpmyadmin package is installed
  apt:
    name: phpmyadmin

- include: nginx.yml
- include: config.yml
